---
# tasks file for elastic_apm_agent

# installation and configuration
# https://www.elastic.co/guide/en/apm/agent/java/current/index.html

- name: create the apm agent directory
  file:
    path: "{{ elastic_apm_java_dir }}"
    state: directory
    owner: root
    group: root
    recurse: yes 

- name: download apm java agent
  get_url:
    url: "{{ elastic_apm_java_url }}"
    dest: "{{ elastic_apm_java_dir }}/elastic-apm-agent-1.10.0.jar"
    mode: '0644'

# instrumenting
#JAVA_APM="-javaagent:/usr/share/apm-agent/java/elastic-apm-agent-1.10.0.jar \
# -Delastic.apm.service_name=asset-manager \
# -Delastic.apm.server_url=http://ops01:8200 \
# -Delastic.apm.secret_token= \
# -Delastic.apm.application_packages=com.openecs"

#$JAVA_HOME/bin/java $JAVA_OPTS $JAVA_APM -jar $JAR_PATH