- name: insert/update configuration using a local file and validate it
  blockinfile:
    block: "{{ lookup('file', 'templates/scrape_configs/scrape-gateway.j2') }}"
    dest: "{{app_dest_dir}}/{{app_version}}/prometheus.yml"
    insertafter: "^scrape_configs:[ ]*$"
    state: present
    marker_begin: "BEGIN gateway"
    marker_end: "END gateway"
    backup: yes