---
# run Debian installation steps

- name: install grafana package from repo.
  apt:
    deb: "{{ grafana_pkg_url }}"
    state: present
  register: grafana_pkg

- name: use grafana configuration templates
  template:
    src: ad.toml.j2
    dest: /etc/grafana/ldap.toml
    backup: no
  notify: restart {{ grafana_daemon_name }}  
  when: grafana_ldap_enabled

- name: use grafana configuration templates
  template:
    src: grafana.ini.j2
    dest: /etc/grafana/grafana.ini
    backup: yes
  notify: restart {{ grafana_daemon_name }} 

- name: enable grafana to start on bootup
  service: name={{ grafana_daemon_name }} enabled=yes state=started 
