---
# run Debian installation steps

- name: install grafana package from repo.
  apt:
    deb: "{{ grafana_pkg_url }}"
    state: present
  register: grafana_pkg

#- name: use grafana configuration templates
#  template:
#    src: 
#    dest: /etc/grafana/
#    backup: yes
#  notify: restart {{ grafana_daemon_name }} 

- name: enable grafana to start on bootup
  service: name={{ grafana_daemon_name }} enabled=yes state=started 
