---
# tasks file for php

#- name: include OS-specific variable file
#  include_vars: "var_{{ ansible_os_family | lower }}.yml"

- name: run OS specific installation
  include: "install_{{ ansible_os_family | lower }}.yml" 

# note checksum may change. this is to ensure the setup script is valid.
- name: download composer setup script
  get_url: 
    url: "https://getcomposer.org/installer"
    dest: "/tmp/composer-setup.php"
    checksum: "sha384:a5c698ffe4b8e849a443b120cd5ba38043260d5c4023dbf93e1558871f1f07f58274fc6f4c93bcfd858c6bd0775cd8d1"

- name: run composer setup script
  command: >
    php /tmp/composer-setup.php --install-dir=/usr/local/bin --filename=composer
