---
# This a test playbook

# Ansible requires Python. Some Linux does not include Python by default. This step is not
# needed if the VM provisioned with Python installed. 
- hosts: all
  become: true
  gather_facts: false

  pre_tasks:
  - name: install python (on Debian family) if not present
    raw: test -e /usr/bin/python || (apt -y update && apt install -y python-minimal)
    when: 1==1

- hosts: all
  become: yes
  gather_facts: true

  roles:
#    - { role: common }
#    - { role: openjdk, openjdk_version: 8 }
#    - { role: php, php_version: 7.3 }
#    - { role: mysql } 
#    - { role: apache2 }
#    - { role: zabbix }
#    - { role: postfix }  
#    - { role: checkmk }
#    - { role: elasticsearch }
#    - { role: kibana }
#    - { role: logstash }    
#    - { role: elastic_apm_server }
    - { role: prometheus } 
#    - { role: grafana } 
  
