---
# tasks file for checkmk_agent

#- name: install the required sytem packages
#  package:
#    name: "{{ item }}"
#    state: present
#  loop:
#      - xinetd

- name: run OS specific installation steps
  include: "install_{{ ansible_os_family | lower }}.yml"
