---
# defaults file for prometheus

# Version History
# https://prometheus.io/download/
# https://github.com/prometheus/prometheus/releases/download/v2.9.1/prometheus-2.9.1.linux-amd64.tar.gz
# http://<hostname>:9090/

# Prometheus
app_env: local
app_name: prometheus
app_version: 2.9.1
app_home: "/data1/{{app_name}}"
app_owner: prometheus
app_group: prometheus

app_pkg_name: "prometheus-{{app_version}}.linux-amd64.tar.gz"
app_pkg_url: "https://github.com/prometheus/prometheus/releases/download/v{{app_version}}/{{app_pkg_name}}"
app_dir_name: "prometheus-{{app_version}}.linux-amd64"

app_src_dir: "/data1/build/{{app_name}}/dist"
app_dest_dir: "{{app_home}}"

# Push Gateway
# https://github.com/prometheus/pushgateway/releases/download/v1.2.0/pushgateway-1.2.0.linux-amd64.tar.gz
prometheus_gateway_name: prometheus-gateway
prometheus_gateway_version: 1.2.0
prometheus_gateway_home: "/data1/{{prometheus_gateway_name}}"

prometheus_gateway_pkg_name: pushgateway-{{prometheus_gateway_version}}.linux-amd64.tar.gz
prometheus_gateway_pkg_url: https://github.com/prometheus/pushgateway/releases/download/v{{prometheus_gateway_version}}/pushgateway-1.2.0.linux-amd64.tar.gz
prometheus_gateway_dir_name: pushgateway-{{prometheus_gateway_version}}.linux-amd64

prometheus_gateway_src_dir: "/data1/build/{{prometheus_gateway_name}}/dist"
prometheus_gateway_dest_dir: "{{prometheus_gateway_home}}"
prometheus_gateway_svc_name: pushgateway


